# Generated by Django 5.2.13 on 2026-05-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=2)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
    ]
